name: doi_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+3
publish_to: none

environment:
  sdk: ^3.5.0
  
dependencies:
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  uuid: ^4.5.1
  device_preview: ^1.2.0
  in_app_purchase: ^3.2.1
  lottie: ^3.3.1
  qr_flutter: ^4.1.0
  device_info_plus: ^10.1.2
  flutter_branch_sdk: ^8.4.1
  share_plus: ^11.0.0
  socket_io_client: ^3.1.1
  google_mobile_ads: ^6.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_app_installations: ^0.3.2+5


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  country_picker: ^2.0.27

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.4.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/jsons/
   

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura-Light.ttf
          weight: 300
    - family: Jungle Adventurer
      fonts:
        - asset: assets/fonts/JungleAdventurer.ttf
          weight: 400
    - family: Rimouski
      fonts:
        - asset: assets/fonts/rimouski.otf
          weight: 600
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700