import 'package:flutter/material.dart';

class AppColors {
  static const Color primaryColor = Color(0xFF1C98E0);
  static const Color secondaryColor = Color(0xFFF81D27);
  static const Color onPrimary = Color(0xFFB3DDF5);
  static const Color fill = Color(0xFFD9D9D9);
  static const Color darklight = Color(0xFF1E1E1E);
  static const Color mediumBlue = Color(0xFFDDE5FF);
  static const Color lightBlue = Color(0xFFEEF6FF);
  static const Color red = Color(0xFFD52929);
  static const Color deepRed = Color(0xFFE10000);
  static const Color deeperRed = Color(0xFFC80000);
  static const Color deepestRed = Color(0xFFC20701);
  static const Color lightRed = Color(0xFFFBE5D7);
  static const Color redLighter = Color(0xFFFFEDED);
  static const Color green = Color(0xFF00D718);
  static const Color greyText = Color(0xFF4D4D4D);
  static const Color lightGreen = Color(0xFFDDE5FF);
  static const Color deepGrey = Color(0xFF8E8E8E);
  static const Color lightGrey = Color(0xFFBEC0C2);
  static const Color grey = Color(0xFF626362);
  static const Color lightYellow = Color(0xFFFFF8ED);
  static const Color white = Color(0xFFFFFFFF);
  static const Color redLight = Color(0xFFFFE5E5);
  static const Color secondaryGrey = Color(0xFFCDCDCE);
  static const Color deepGreen = Color(0xFF091E05);
  static const Color text = Color(0xFF404652);
  static const Color mint = Color(0xFFDFEFD4);
  static const Color textGrey = Color(0xFF474747);
  static const Color blue = Color(0xFF304FFE);
  static const Color completed = Color(0xFFE5F5DC);
  static const Color card = Color(0xFFD9D9D9);
  static const Color noti = Color(0xFFE9E4E4);
  static const Color cardGrey = Color(0xFFECECEC);
  static const Color pending = Color(0xFFF5ECDC);
  static const Color border = Color(0xFFE7E7E7);
  static const Color hint = Color(0xFF505661);
  static const Color textNew = Color(0xFF31373D);
  static const Color background = Color(0xFFFFF5EF);
}
